import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 *
 *  The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 *  Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    {
      type: 'category',
      label: 'SUBFROST Overview',
      items: [
        'index',
        'frbtc-overview',
        'dxbtc-overview',
        'frost-token',
      ],
    },
    {
      type: 'category',
      label: 'Technical User Guide',
      items: [
        'user-guide/getting-started',
        'user-guide/creating-a-keystore',
        'user-guide/wrapping-frbtc',
        'user-guide/building-subrail-programs',
        'user-guide/amm',
      ],
    },
    {
      type: 'category',
      label: 'Security & Architecture',
      items: [
        'developer-guide/technical-overview',
        'developer-guide/frost-protocol',
        
        'developer-guide/proof-of-stake',
        'developer-guide/subrail',
      ],
    },
    {
        type: 'category',
        label: 'Supported Bitcoin Ecos',
        items: [
            'developer-guide/alkanes',
            'developer-guide/BRC 2.0 Metaprotocol',
            
'developer-guide/Arch Network',
        ],
    },
    {
        type: 'category',
        label: 'References',
        items: [
            'references/subfrost-node-cli',
            'references/subrail-cli',
        ],
    }
  ],
};

export default sidebars;
