// Chadlina: Forcing a change to trigger git
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 *
 *  The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 *  Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docs: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    {
      type: 'category',
      label: 'Start Here',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'start-here'}],
    },
    {
      type: 'category',
      label: 'Using SUBFROST',
      items: [{type: 'autogenerated', dirName: 'using-subfrost'}],
    },
    {
      type: 'category',
      label: 'Tokens & Economics',
      items: [
        // Was `{type: 'autogenerated', dirName: 'tokens-economics'}`. Listed
        // explicitly since 2026-07-29 so DIESEL can be hidden from the nav at
        // Gabe's request WITHOUT deleting it: docs/tokens-economics/diesel.md
        // and its URL are untouched, and the Tokens & Economics overview still
        // links to it. Same shape as the SUBFROST APP block below. Restoring
        // it to the nav is adding 'tokens-economics/diesel' back here.
        'tokens-economics/overview',
        {
          type: 'doc',
          id: 'tokens/frBTC-overview',
          label: 'frBTC - Defi-compatible BTC',
        },
        {
          type: 'doc',
          id: 'tokens/frUSD-overview',
          label: 'frUSD - Ultimate Stablecoin',
        },
        {
          type: 'doc',
          id: 'tokens/dxBTC-overview',
          label: 'dxBTC - Yield-bearing BTC',
        },
        // No explicit label: this page carries its own `sidebar_label` in both
        // locales ("dxBTC - Minting/Burning" and "dxBTC - 铸造/销毁"), and the
        // frontmatter wins over a label set here, so an override would be dead
        // weight that reads as if it were in force.
        'tokens/minting-dxBTC',
        {
          type: 'doc',
          id: 'tokens/FUEL-token',
          label: 'FUEL - Protocol Token',
        },
      ],
    },
    // SUBFROST APP: hidden from the nav on 2026-07-15, NOT deleted. The pages and their URLs are
    // untouched; only the sidebar entry is commented out. Restoring is uncommenting this block.
    //
    // Why: these are the originals of the pages now merged into Using SUBFROST, and Gabe asked
    // whether this section should go. Until he decides (and until the redirect question is settled),
    // serving both meant serving two answers to the same question, and the old ones are now the
    // wrong answer: subfrost-app/swap says "3-block confirmation period" where the team has since
    // told us 3 to 7, and subfrost-app/wallet offers Signet and Regtest to end users, which Vitor
    // removed on 2026-07-15. A reader with the link cannot tell which page is canon.
    //
    // {
    //   type: 'category',
    //   label: 'SUBFROST APP',
    //   items: [
    //     'subfrost-app/overview',
    //     'subfrost-app/swap',
    //     {
    //       type: 'category',
    //       label: 'DeFi Vaults on Bitcoin',
    //       link: { type: 'doc', id: 'subfrost-app/vaults' },
    //       items: [
    //         'subfrost-app/fire-vault',
    //       ],
    //     },
    //     'subfrost-app/futures',
    //     'subfrost-app/wallet',
    //   ]
    // },
    // KEY COMPONENTS: added to the nav on 2026-08-03. These six pages were built
    // and shipped but never had a sidebar entry, so they rendered with no sidebar
    // and were reachable only through body links from pages that ARE in the nav
    // (tokens/frBTC-overview points at frost-and-roast and alkanes; the developer
    // guide points at alkanes and brc20-prog). Gabe found frost-and-roast that way
    // and asked whether it was a page we meant to present.
    //
    // Listed explicitly rather than autogenerated: only three of the six carry a
    // sidebar_position, so autogeneration would put the other three in alphabetical
    // order after them, which is not the order a reader wants.
    {
      type: 'category',
      label: 'Key Components',
      items: [
        'key-components/alkanes',
        'key-components/brc20-prog',
        'key-components/frost-and-roast',
        'key-components/schnorr-signatures',
        'key-components/keystore-management',
        'key-components/lending',
      ],
    },
    {
      type: 'category',
      label: 'Technical Overview',
      items: [{type: 'autogenerated', dirName: 'protocol'}],
    },
    {
      type: 'category',
      label: 'Build on SUBFROST',
      items: [{type: 'autogenerated', dirName: 'build'}],
    },
    // DEVELOPER GUIDE: same story as Key Components, four pages. Its own category
    // rather than folded into Build on SUBFROST, so the two autogenerated blocks
    // keep their own sidebar_position ordering instead of interleaving.
    {
      type: 'category',
      label: 'Developer Guide',
      items: [{type: 'autogenerated', dirName: 'developer-guide'}],
    },
    {
      type: 'category',
      label: 'API & SDK Docs',
      items: [{type: 'autogenerated', dirName: 'api-reference'}],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/glossary',
      ]
    },
  ],
};

export default sidebars;
