// Chadlina: Forcing a change to trigger git
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 *
 *  The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 *  Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docs: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    {
      type: 'category',
      label: 'Introduction',
      items: [
        'introduction/1.1-SUBFROST-Overview',
        {
          type: 'doc',
          id: 'introduction/1.2-technical-overview',
          label: 'Technical Overview',
        },
        'introduction/1.3-getting-started',
      ]
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'core-concepts/2.1-alkanes',
        'core-concepts/2.2-frost-and-roast',
        'core-concepts/2.3-schnorr-signatures',
        'core-concepts/2.4-keystore-management',
        'core-concepts/2.5-Proof-of-Stake',
      ]
    },
    {
      type: 'category',
      label: 'Subfrost Networking',
      items: [
        'subfrost-networking/3.1-introduction-to-subp2p',
        'subfrost-networking/3.2-subrelay',
        'subfrost-networking/3.3-subproxy',
        'subfrost-networking/3.4-subtun',
        'subfrost-networking/3.5-gossipsub-and-encrypted-communication',
        'subfrost-networking/3.6-building-microservices-on-subp2p',
      ]
    },
    {
      type: 'category',
      label: 'Tokens',
      items: [
        'tokens/4.1-fr-btc',
        'tokens/4.2-frBTC-Roadmap',
        'tokens/4.3-Wrapping-FrBTC',
        'tokens/4.4-Fr-BTC-Smart-Contracts',
        'tokens/4.5-Dx-BTC',
        'tokens/4.6-FROST-Token',
      ]
    },
    {
      type: 'category',
      label: 'Developer Guide',
      items: [
        'developer-guide/5.1-Subfrost-CLI',
        'developer-guide/5.2-Subfrost-Runtime',
        'developer-guide/5.3-subrail',
        'developer-guide/5.4-SubSwap',
      ]
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/6.1-subfrost-node-cli-reference',
        'reference/6.2-subfrost-cli-reference',
        'reference/6.3-Subrail-CLI-Reference',
        'reference/6.4-Glossary',
      ]
    },
  ],
};

export default sidebars;
